### Server ###
server:
  port: 8761

### Spring ###
spring:

  ### Application ###
  application:
    name: eureka-server

  ### Security ###
  security:
    user:
      name: user
      password: 1111

### Eureka ###
eureka:
  dashboard:
    enabled: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
    home-page-url: https://${eureka.hostname}/
    status-page-url: https://${eureka.hostname}/info
    health-check-url: https://${eureka.hostname}/health
  #    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
