### Server ###
server:
  port: 8761

### Spring ###
spring:

  config:
    ### Active on profile ###
    activate:
      on-profile: default

  ### Application ###
  application:
    name: eureka-server

  ### Security ###
  security:
    user:
      name: user
      password: 1111

### Eureka ###
eureka:
  dashboard:
    enabled: true
  instance:
    hostname: localhost
#    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
