### Server ###
server:
  port: 8761

### Spring ###
spring:

  ### Application ###
  application:
    name: eureka-server

  ### Security ###
  security:
    user:
      name: user
      password: 1111

  ### Banner ###
  banner:
    location: banner/banner-3-d.txt

### Eureka ###
eureka:
  dashboard:
    enabled: on
  instance:
    hostname: localhost
  #    prefer-ip-address: false
  client:
    fetch-registry: off
    register-with-eureka: off
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
